### ISSUE TITLE
返回按钮的点击

### ISSUE THREAD

**Issue by baiRookie** [CoderZZHe/HZNavigationBar#10]
发现你这个导航蓝按钮点击极其难点击，建议大小写死，根据图片大小点击不太靠谱

**Comment by Boxzhi** [comment]
我自己项目中用了这么久都ok的啊，默认宽高44

**Comment by Boxzhi** [comment]
> 发现你这个导航蓝按钮点击极端难点击，建议大小写死，根据图片大小点击不太靠谱

我自己项目中用了这么久都ok的啊，默认宽高44

**Comment by BeingCode** [comment]
建议title的设置改为直接开放titleLabel这样灵活度会更高
