### ISSUE TITLE
关于title属性设置(titleColor等)

### ISSUE THREAD

**Issue by BeingCode** [CoderZZHe/HZNavigationBar#11]
建议title的设置改为直接开放titleLabel这样灵活度会更高

//    /// navigationBar的title
//    public var title: String? {
//        willSet {
//            hz_setTitleLabel(newValue, textColor: titleColor, font: titleFont)
//        }
//    }
//
//    /// navigationBar的title颜色
//    public var titleColor: UIColor = HZDefaultTitleColor {
//        willSet {
//            hz_setTitleLabel(title, textColor: newValue, font: titleFont)
//        }
//    }
//
//    /// navigationBar的title字体
//    public var titleFont: UIFont = UIFont.systemFont(ofSize: HZDefaultTitleSize) {
//        willSet {
//            hz_setTitleLabel(title, textColor: titleColor, font: newValue)
//        }
//    }

**Comment by Boxzhi** [comment]
谢谢你的建议，我会考虑放开attributedText属性
