### ISSUE TITLE
有无打算适配横向？

### ISSUE THREAD

**Issue by League2EB** [CoderZZHe/HZNavigationBar#2]
觉得您写的不错，但我打开Demo并且开启横向配置后发现会有该问题
![](https://i.loli.net/2019/12/18/85HwhAvd3kBEguM.png)
不知道什么时候有打算更新横向的支持？

**Comment by Boxzhi** [comment]
给我点时间，最近在忙项目，会抽空尽快~

**Comment by League2EB** [comment]
辛苦您了，加油！
