### ISSUE TITLE
iPad 的适配问题

### ISSUE THREAD

**Issue by XinYangLK** [CoderZZHe/HZNavigationBar#4]
首先没有什么比star更支持了,另外希望作者能增加demo使用案例,最起码是贴出来的效果案例!更加能指导方便使用者的使用,有利于推广!
在看作者的作品里,iPad pro11横屏适配中,导航无法铺满.相信在其他型号iPad中也是一样,看了作者设置可能并没有适配iPad,也希望作者有时间能跟进
再次感谢🙏作者贡献

**Comment by Boxzhi** [comment]
你说的增加demo案例我会考虑的😁 暂时确实没有做iPad的适配，后续有空会考虑的
