### ISSUE TITLE
可以单独设置状态栏颜色吗？

### ISSUE THREAD

**Issue by BeingCode** [CoderZZHe/HZNavigationBar#7]

**Comment by Boxzhi** [comment]
可以

**Comment by Boxzhi** [comment]
可以
/// navigationBar背景颜色
public var barBackgroundColor: UIColor?

**Comment by Boxzhi** [comment]
可以
`/// navigationBar背景颜色
 public var barBackgroundColor: UIColor?`

**Comment by BeingCode** [comment]
statusbar

**Comment by Boxzhi** [comment]
暂时没有

**Comment by BeingCode** [comment]
可以支持一下单独设置statusbar背景颜色吗？

**Comment by Boxzhi** [comment]
这个需求确实不常见，我这段时间空了看看

**Comment by Boxzhi** [comment]
v1.3.0已支持
